version: 0.2
env:
  exported-variables:
    - APP_NAME
    - APP_VERSION
    - APP_ENVIRONMENT
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - aws s3 cp s3://$BUCKET_NAME/config/$APP_ENVIRONMENT/template.json ./template.json
      - aws s3 cp s3://$BUCKET_NAME/artifacts/superapp-core-redsocial-0.1.2.jar ./superapp-core-redsocial-0.1.2.jar
      - aws s3 cp s3://$BUCKET_NAME/artifacts/superapp-core-neptune-2.0.3.jar ./superapp-core-neptune-2.0.3.jar
      - aws s3 cp s3://$BUCKET_NAME/artifacts/superapp-core-microservice-1.0.0.jar ./superapp-core-microservice-1.0.0.jar
      - mvn install:install-file -Dfile=./superapp-core-microservice-1.0.0.jar -DgroupId=com.superapp.core -DartifactId=superapp-core-microservice -Dversion=1.0.0 -Dpackaging=jar
      - mvn install:install-file -Dfile=./superapp-core-redsocial-0.1.2.jar  -DgroupId=com.superapp.redsocial -DartifactId=redsocial-core -Dversion=0.1.2 -Dpackaging=jar
      - mvn install:install-file -Dfile=./superapp-core-neptune-2.0.3.jar -DgroupId=com.superapp.core -DartifactId=neptune -Dversion=2.0.3 -Dpackaging=jar
      - mvn package
  build:
    commands:
      - APP_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.name -q -DforceStdout)
      - APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)
      - ARTIFACT_NAME=$APP_NAME-$APP_VERSION.jar
      - unzip dist/$ARTIFACT_NAME -d dist
  post_build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET_NAME --output-template-file outputtemplate.yml --kms-key-id $KMS_KEY_ID --s3-prefix $APP_NAME/Artifacts
artifacts:
  files:
    - template.yml
    - outputtemplate.yml
    - template.json